package com.example.Camera_Project.model;

import lombok.Data;

@Data
public class Choice {

	private String text;
	private Integer index;
//	@JsonProperty("finish_reason")
	private String finish_reason;
}
/*Choices: It is this component of OpenAI API Response which contains the output we seek. 
The choice component will have a text parameter which holds the answer generated by ChatGPT for the requested user prompt. */

    //@JsonProperty is used to specify the property name in a JSON object when serializing or deserializing an object using Jackson. 
    //This annotation is used to map the property name in the Java object to the property name in the JSON object.